// Banco de jugadores históricos - Adivina el Jugador
// pistas: ordenadas de más difícil/genérica a más fácil/específica
const BANCO_JUGADORES = [
  { nombre: "Diego Maradona", pistas: ["Ganó un Mundial como capitán.", "Es argentino.", "Jugó en Boca Juniors y Napoli.", "Anotó el 'Gol del Siglo' en 1986.", "Es conocido como 'El Pibe de Oro'."] },
  { nombre: "Lionel Messi", pistas: ["Ganó un Mundial.", "Jugó en Barcelona.", "Es argentino.", "Tiene 8 Balones de Oro.", "Es apodado 'La Pulga' y jugó en PSG e Inter Miami."] },
  { nombre: "Pelé", pistas: ["Ganó tres Mundiales.", "Es brasileño.", "Jugó toda su carrera en Santos.", "Marcó más de 1000 goles en su carrera.", "Es considerado 'O Rei' del fútbol."] },
  { nombre: "Cristiano Ronaldo", pistas: ["Ganó una Eurocopa.", "Jugó en Manchester United.", "Es portugués.", "Jugó en Real Madrid y Juventus.", "Es el máximo goleador histórico del fútbol masculino."] },
  { nombre: "Zinedine Zidane", pistas: ["Ganó un Mundial.", "Es francés.", "Jugó en Real Madrid.", "Fue expulsado en la final de 2006 por un cabezazo.", "Hoy es reconocido también como entrenador del Real Madrid."] },
  { nombre: "Ronaldo Nazário", pistas: ["Ganó dos Mundiales.", "Es brasileño.", "Jugó en Barcelona, Inter y Real Madrid.", "Fue goleador del Mundial 2002.", "Es apodado 'El Fenómeno'."] },
  { nombre: "Ronaldinho", pistas: ["Ganó un Mundial.", "Es brasileño.", "Jugó en Barcelona.", "Ganó el Balón de Oro en 2005.", "Es conocido por sus jugadas de fantasía y su sonrisa."] },
  { nombre: "Johan Cruyff", pistas: ["Jugó dos finales de Mundial sin ganar.", "Es holandés.", "Jugó en Ajax y Barcelona.", "Fue figura de 'La Naranja Mecánica' en 1974.", "Tiene una jugada de gambeta que lleva su nombre."] },
  { nombre: "Franz Beckenbauer", pistas: ["Ganó un Mundial como jugador y otro como entrenador.", "Es alemán.", "Jugó en Bayern Múnich.", "Fue defensor, pero se le apodaba 'El Káiser'.", "Capitaneó a Alemania campeona en 1974."] },
  { nombre: "Michel Platini", pistas: ["Ganó una Eurocopa como jugador.", "Es francés.", "Jugó en Juventus.", "Ganó tres Balones de Oro consecutivos.", "Después fue presidente de la UEFA."] },
  { nombre: "George Best", pistas: ["No jugó ningún Mundial con su selección.", "Es de Irlanda del Norte.", "Jugó en Manchester United.", "Era conocido por su estilo de vida extravagante.", "Se le comparaba con 'El quinto Beatle'."] },
  { nombre: "Alfredo Di Stéfano", pistas: ["Jugó para tres selecciones distintas.", "Nació en Argentina pero jugó por España.", "Jugó en Real Madrid.", "Ganó cinco Copas de Europa consecutivas.", "Es apodado 'La Saeta Rubia'."] },
  { nombre: "Garrincha", pistas: ["Ganó dos Mundiales.", "Es brasileño.", "Jugó en Botafogo.", "Tenía una pierna más corta que la otra.", "Es apodado 'Alegría del Pueblo'."] },
  { nombre: "Eusébio", pistas: ["Fue goleador de un Mundial sin ganarlo.", "Es portugués (nacido en Mozambique).", "Jugó en Benfica.", "Fue figura clave del Mundial de 1966.", "Es apodado 'La Pantera Negra'."] },
  { nombre: "Roberto Baggio", pistas: ["Perdió una final de Mundial en penales.", "Es italiano.", "Jugó en Juventus y Milan.", "Ganó el Balón de Oro en 1993.", "Es conocido por su coleta y su penal fallado en 1994."] },
  { nombre: "Paolo Maldini", pistas: ["Nunca ganó un Mundial.", "Es italiano.", "Jugó toda su carrera en Milan.", "Es considerado uno de los mejores defensores de la historia.", "Su hijo Daniel también es futbolista profesional."] },
  { nombre: "Gerd Müller", pistas: ["Ganó un Mundial.", "Es alemán.", "Jugó en Bayern Múnich.", "Fue goleador del Mundial 1970.", "Es el segundo máximo goleador histórico de Mundiales."] },
  { nombre: "Lothar Matthäus", pistas: ["Ganó un Mundial como capitán.", "Es alemán.", "Jugó en Bayern Múnich e Inter.", "Jugó cinco Copas del Mundo distintas.", "Ganó el primer Balón de Oro mundial (FIFA) en 1991."] },
  { nombre: "Marco van Basten", pistas: ["Ganó una Eurocopa.", "Es holandés.", "Jugó en Ajax y Milan.", "Anotó un gol de volea espectacular en la final de 1988.", "Su carrera terminó joven por lesiones de tobillo."] },
  { nombre: "Thierry Henry", pistas: ["Ganó un Mundial.", "Es francés.", "Jugó en Arsenal y Barcelona.", "Es el máximo goleador histórico de Arsenal.", "Fue conocido por su velocidad y definición en la Premier League."] },
  { nombre: "Andrés Iniesta", pistas: ["Ganó un Mundial.", "Es español.", "Jugó en Barcelona.", "Anotó el gol del título en la final del Mundial 2010.", "Formó parte de la generación dorada de España junto a Xavi."] },
  { nombre: "Xavi Hernández", pistas: ["Ganó un Mundial.", "Es español.", "Jugó en Barcelona.", "Fue el mediocampista organizador de la 'Roja' campeona.", "Hoy es entrenador del Barcelona."] },
  { nombre: "David Villa", pistas: ["Ganó un Mundial.", "Es español.", "Jugó en Valencia y Barcelona.", "Es el máximo goleador histórico de la selección española.", "Anotó goles clave en el Mundial 2010."] },
  { nombre: "Iker Casillas", pistas: ["Ganó un Mundial como capitán.", "Es español.", "Jugó toda su carrera en Real Madrid antes de ir al Porto.", "Es apodado 'San Iker'.", "Levantó la Copa del Mundo en Sudáfrica 2010."] },
  { nombre: "Luis Suárez", pistas: ["No ha ganado un Mundial.", "Es uruguayo.", "Jugó en Liverpool y Barcelona.", "Fue sancionado por morder a un rival en el Mundial 2014.", "Forma un trío histórico con Cavani y Forlán en la selección charrúa."] },
  { nombre: "Diego Forlán", pistas: ["No ganó un Mundial pero fue el mejor jugador de uno.", "Es uruguayo.", "Jugó en Villarreal e Inter de Milán.", "Ganó el Balón de Oro del Mundial 2010.", "Su padre también fue futbolista uruguayo."] },
  { nombre: "Zico", pistas: ["Nunca ganó un Mundial.", "Es brasileño.", "Jugó en Flamengo.", "Fue apodado 'El Pelé Blanco'.", "Brilló en los Mundiales de 1982 y 1986."] },
  { nombre: "Sócrates", pistas: ["Nunca ganó un Mundial.", "Es brasileño.", "Jugó en Corinthians.", "Era médico además de futbolista.", "Fue capitán del histórico equipo brasileño de 1982."] },
  { nombre: "Carlos Valderrama", pistas: ["Nunca ganó un Mundial.", "Es colombiano.", "Jugó en Montpellier y varios clubes de EE.UU.", "Es reconocido por su cabello rizado y rubio.", "Es apodado 'El Pibe'."] },
  { nombre: "Faustino Asprilla", pistas: ["Nunca ganó un Mundial.", "Es colombiano.", "Jugó en Newcastle y Parma.", "Anotó goles clave en la Champions League con Newcastle.", "Es apodado 'Tino'."] },
  { nombre: "Hugo Sánchez", pistas: ["Jugó un Mundial sin ganarlo.", "Es mexicano.", "Jugó en Real Madrid.", "Es el máximo goleador histórico de la liga española en un club extranjero.", "Era famoso por celebrar sus goles con saltos mortales."] },
  { nombre: "Rafael Márquez", pistas: ["Jugó cuatro Mundiales con México.", "Es mexicano.", "Jugó en Barcelona y Monaco.", "Fue capitán histórico de la selección mexicana.", "Es el único mexicano en ganar la Champions League como titular."] },
  { nombre: "Paulo Wanchope", pistas: ["Jugó dos Mundiales.", "Es costarricense.", "Jugó en Derby County y West Ham.", "Es el máximo goleador histórico de Costa Rica.", "Hoy ha sido director técnico de la selección costarricense."] },
  { nombre: "Keylor Navas", pistas: ["Jugó tres Mundiales como portero titular.", "Es costarricense.", "Jugó en Real Madrid y PSG.", "Fue héroe en los penales del Mundial 2014.", "Ganó tres Champions League consecutivas con el Real Madrid."] },
  { nombre: "Bryan Ruiz", pistas: ["Jugó tres Mundiales con su selección.", "Es costarricense.", "Jugó en PSV y Fulham.", "Fue capitán de Costa Rica en Brasil 2014.", "Anotó un gol clave de cabeza ante Italia en 2014."] },
  { nombre: "Joel Campbell", pistas: ["Jugó dos Mundiales con su selección.", "Es costarricense.", "Jugó en Arsenal y Olympiacos.", "Fue clave en el histórico Mundial de Brasil 2014.", "Es conocido por su explosividad como extremo."] },
  { nombre: "Rolando Fonseca", pistas: ["Jugó un Mundial con su selección.", "Es costarricense.", "Jugó la mayor parte de su carrera en clubes de Costa Rica y México.", "Fue máximo goleador histórico de Costa Rica antes de Wanchope.", "Su apodo es 'El Cabezón'."] },
  { nombre: "Romário", pistas: ["Ganó un Mundial.", "Es brasileño.", "Jugó en Barcelona.", "Anotó más de 1000 goles en su carrera, según sus registros.", "Fue clave junto a Bebeto en el Mundial de 1994."] },
  { nombre: "Bebeto", pistas: ["Ganó un Mundial.", "Es brasileño.", "Jugó en Deportivo La Coruña.", "Celebró un gol simulando 'mecer una cuna' en 1994.", "Formó dupla goleadora con Romário."] },
  { nombre: "Cafú", pistas: ["Ganó dos Mundiales.", "Es brasileño.", "Jugó en Roma y Milan.", "Es el único jugador en disputar tres finales de Mundial consecutivas.", "Jugaba como lateral derecho."] },
  { nombre: "Roberto Carlos", pistas: ["Ganó un Mundial.", "Es brasileño.", "Jugó en Real Madrid.", "Es famoso por un tiro libre imposible contra Francia en 1997.", "Jugaba como lateral izquierdo con tiros muy potentes."] },
  { nombre: "Kaká", pistas: ["Ganó un Mundial.", "Es brasileño.", "Jugó en Milan y Real Madrid.", "Ganó el Balón de Oro en 2007.", "Era conocido por su estilo elegante y caballeroso."] },
  { nombre: "Neymar", pistas: ["No ha ganado un Mundial.", "Es brasileño.", "Jugó en Barcelona y PSG.", "Es el máximo goleador histórico de la selección brasileña.", "Su transferencia al PSG fue la más cara de la historia."] },
  { nombre: "Kylian Mbappé", pistas: ["Ganó un Mundial.", "Es francés.", "Jugó en Mónaco y PSG.", "Anotó un hat-trick en la final del Mundial 2022.", "Hoy juega en el Real Madrid."] },
  { nombre: "Antoine Griezmann", pistas: ["Ganó un Mundial.", "Es francés.", "Jugó en Atlético de Madrid.", "Fue subcampeón de la Eurocopa 2016 como figura.", "Es conocido por su característica celebración de 'Fortnite'."] },
  { nombre: "Luka Modric", pistas: ["No ha ganado un Mundial pero fue el mejor jugador de uno.", "Es croata.", "Jugó en Real Madrid.", "Ganó el Balón de Oro del Mundial 2018.", "Ganó el Balón de Oro (Ballon d'Or) en 2018."] },
  { nombre: "Davor Suker", pistas: ["No ganó un Mundial pero fue su goleador.", "Es croata.", "Jugó en Real Madrid y Sevilla.", "Fue el máximo goleador del Mundial de 1998.", "Llevó a Croacia a semifinales en su primer Mundial."] },
  { nombre: "Andrés Escobar", pistas: ["Jugó un Mundial sin ganarlo.", "Es colombiano.", "Jugó en Atlético Nacional.", "Marcó un autogol decisivo en el Mundial de 1994.", "Fue asesinado tras regresar del torneo, un hecho que marcó al fútbol mundial."] },
  { nombre: "James Rodríguez", pistas: ["No ha ganado un Mundial pero fue su goleador.", "Es colombiano.", "Jugó en Mónaco y Real Madrid.", "Fue el máximo goleador del Mundial 2014.", "Anotó un golazo de volea ante Uruguay en octavos de 2014."] },
  { nombre: "Emiliano Martínez", pistas: ["Ganó un Mundial.", "Es argentino.", "Jugó en Arsenal y Aston Villa.", "Ganó el Guante de Oro del Mundial 2022.", "Es conocido por sus atajadas decisivas en penales y su apodo 'Dibu'."] },
];

if (typeof module !== "undefined") module.exports = BANCO_JUGADORES;
