// Banco de acciones para el juego de Mímica (Día del Padre)
// Acciones cotidianas, divertidas y fáciles de actuar sin hablar y sin usar objetos reales.
const BANCO_MIMICA = [
  "Pasear a la mascota",
  "Viendo televisión",
  "Cocinando un asado/parrillada",
  "Lavando los platos",
  "Manejando un carro",
  "Tocando la guitarra",
  "Jugando videojuegos",
  "Pescando",
  "Cortando el césped",
  "Afeitándose",
  "Tomando una foto",
  "Bailando en una fiesta",
  "Nadando en la piscina",
  "Andando en bicicleta",
  "Durmiendo y roncando",
  "Leyendo un periódico",
  "Haciendo ejercicio en el gimnasio",
  "Tomando café caliente",
  "Hablando por teléfono",
  "Pintando una pared",
  "Armando un mueble con instrucciones complicadas",
  "Lavando el carro",
  "Jugando fútbol",
  "Jugando baloncesto",
  "Boxeando",
  "Surfeando una ola",
  "Esquiando en la nieve",
  "Patinando sobre hielo",
  "Cantando en la ducha",
  "Peinándose frente al espejo",
  "Manejando una moto",
  "Remando en una canoa",
  "Haciendo yoga",
  "Levantando pesas pesadas",
  "Tejiendo una bufanda",
  "Plantando flores en el jardín",
  "Pintando un cuadro",
  "Tomando una siesta en el sofá",
  "Comiendo espagueti sin tenedor",
  "Pelando una banana",
  "Estornudando muy fuerte",
  "Teniendo hipo sin control",
  "Haciendo burbujas de jabón",
  "Volando una cometa",
  "Saltando la cuerda",
  "Haciendo malabares con pelotas",
  "Tocando el piano",
  "Tocando la batería",
  "Disparando con arco y flecha",
  "Esquivando una pelota que viene volando",
  "Pateando un balón al arco",
  "Atrapando una pelota en el aire",
  "Imitando a un mono comiendo",
  "Imitando a un robot caminando",
  "Pilotando un avión",
  "Remando un bote en una tormenta",
  "Lavando ropa a mano en un balde",
  "Limpiando ventanas",
  "Barriendo el piso",
  "Aspirando la alfombra",
  "Tendiendo la ropa en el patio",
  "Apagando un incendio con un extintor",
  "Subiendo una escalera muy alta",
  "Bajando una escalera con miedo",
  "Haciendo snowboard",
  "Comiendo un helado que se derrite rápido",
  "Tratando de abrir un frasco muy apretado",
  "Buscando las llaves perdidas",
  "Armando una tienda de campaña",
  "Asando malvaviscos en una fogata",
  "Manejando un control remoto que no funciona",
  "Tratando de tomarse una selfie perfecta",
  "Cargando muchas bolsas del supermercado",
  "Cambiando una llanta pinchada",
  "Tratando de dormir a un bebé que llora",
  "Echando gasolina al carro",
  "Haciendo una parrillada y quemándose el dedo",
  "Buscando el control remoto entre los cojines del sofá",
];

if (typeof module !== "undefined") module.exports = BANCO_MIMICA;
