// Banco de preguntas - Trivia Mundialista (Copas del Mundo FIFA)
// Cada pregunta: { pregunta, opciones: [4], correcta: indice }
const BANCO_TRIVIA = [
  { pregunta: "¿Qué país ha ganado más Copas del Mundo?", opciones: ["Alemania", "Brasil", "Argentina", "Italia"], correcta: 1 },
  { pregunta: "¿En qué Mundial debutó la Selección de Costa Rica?", opciones: ["Italia 1990", "España 1982", "México 1986", "USA 1994"], correcta: 0 },
  { pregunta: "¿Quién ganó el Mundial 2006?", opciones: ["Francia", "Brasil", "Italia", "España"], correcta: 2 },
  { pregunta: "¿Qué jugador tiene más goles en la historia de los Mundiales?", opciones: ["Pelé", "Miroslav Klose", "Ronaldo Nazário", "Just Fontaine"], correcta: 1 },
  { pregunta: "¿En qué país se jugó el primer Mundial de fútbol?", opciones: ["Brasil", "Francia", "Uruguay", "Italia"], correcta: 2 },
  { pregunta: "¿En qué año se jugó el primer Mundial?", opciones: ["1928", "1930", "1934", "1938"], correcta: 1 },
  { pregunta: "¿Quién ganó el Mundial de 1930?", opciones: ["Argentina", "Uruguay", "Brasil", "Italia"], correcta: 1 },
  { pregunta: "¿Cuántas veces ha sido campeón Brasil?", opciones: ["3", "4", "5", "6"], correcta: 2 },
  { pregunta: "¿Cuántas veces ha sido campeón Argentina?", opciones: ["2", "3", "4", "5"], correcta: 2 },
  { pregunta: "¿Quién ganó el Mundial de Qatar 2022?", opciones: ["Francia", "Argentina", "Croacia", "Brasil"], correcta: 1 },
  { pregunta: "¿Quién fue el goleador del Mundial 2022?", opciones: ["Lionel Messi", "Kylian Mbappé", "Olivier Giroud", "Julián Álvarez"], correcta: 1 },
  { pregunta: "¿En qué estadio se jugó la final del Mundial 2014?", opciones: ["Maracaná", "Mineirão", "Beira-Rio", "Arena Corinthians"], correcta: 0 },
  { pregunta: "¿Qué selección ganó el Mundial 2014?", opciones: ["Argentina", "Holanda", "Alemania", "Brasil"], correcta: 2 },
  { pregunta: "¿Qué jugador anotó el 'Gol del Siglo' en el Mundial de México 1986?", opciones: ["Diego Maradona", "Jorge Valdano", "Mario Kempes", "Gabriel Batistuta"], correcta: 0 },
  { pregunta: "¿Cuál fue la sede del Mundial de 1986?", opciones: ["España", "Colombia", "México", "Argentina"], correcta: 2 },
  { pregunta: "¿Qué país organizó el Mundial de 1994?", opciones: ["Estados Unidos", "México", "Canadá", "Brasil"], correcta: 0 },
  { pregunta: "¿Qué país organizó el Mundial de 1998?", opciones: ["Alemania", "Francia", "Italia", "Inglaterra"], correcta: 1 },
  { pregunta: "¿Quién ganó el Mundial de Francia 1998?", opciones: ["Brasil", "Francia", "Croacia", "Holanda"], correcta: 1 },
  { pregunta: "¿Qué país organizó el Mundial de 2002?", opciones: ["Japón y Corea del Sur", "China", "Australia", "Tailandia"], correcta: 0 },
  { pregunta: "¿Quién ganó el Mundial 2002?", opciones: ["Alemania", "Turquía", "Brasil", "Corea del Sur"], correcta: 2 },
  { pregunta: "¿Quién ganó el Mundial de Sudáfrica 2010?", opciones: ["Holanda", "España", "Alemania", "Uruguay"], correcta: 1 },
  { pregunta: "¿Quién anotó el gol de la victoria en la final del Mundial 2010?", opciones: ["David Villa", "Andrés Iniesta", "Xavi Hernández", "Fernando Torres"], correcta: 1 },
  { pregunta: "¿Qué país organizó el Mundial de 2018?", opciones: ["Rusia", "Qatar", "Brasil", "Polonia"], correcta: 0 },
  { pregunta: "¿Quién ganó el Mundial de Rusia 2018?", opciones: ["Croacia", "Bélgica", "Francia", "Inglaterra"], correcta: 2 },
  { pregunta: "¿Cuántos países participan en la fase final del Mundial desde 1998 a 2022?", opciones: ["24", "28", "32", "48"], correcta: 2 },
  { pregunta: "¿Desde qué Mundial participarán 48 selecciones?", opciones: ["2022", "2026", "2030", "2034"], correcta: 1 },
  { pregunta: "¿Qué selecciones organizarán el Mundial 2026?", opciones: ["Estados Unidos, México y Canadá", "Solo Estados Unidos", "México y Brasil", "Canadá y Estados Unidos"], correcta: 0 },
  { pregunta: "¿Qué jugador ganó el Balón de Oro del Mundial 2022?", opciones: ["Kylian Mbappé", "Lionel Messi", "Luka Modric", "Antoine Griezmann"], correcta: 1 },
  { pregunta: "¿Cuántos Mundiales ha ganado Italia?", opciones: ["2", "3", "4", "5"], correcta: 2 },
  { pregunta: "¿Cuántos Mundiales ha ganado Alemania?", opciones: ["2", "3", "4", "5"], correcta: 2 },
  { pregunta: "¿Qué país ganó el Mundial de 1934?", opciones: ["Italia", "Checoslovaquia", "Alemania", "Austria"], correcta: 0 },
  { pregunta: "¿Qué país ganó el Mundial de 1938?", opciones: ["Brasil", "Hungría", "Italia", "Suecia"], correcta: 2 },
  { pregunta: "¿En qué año no se jugó Mundial por la Segunda Guerra Mundial (faltaron dos ediciones)?", opciones: ["1942 y 1946", "1940 y 1944", "1941 y 1945", "1943 y 1947"], correcta: 0 },
  { pregunta: "¿Qué país ganó el Mundial de 1950?", opciones: ["Brasil", "Uruguay", "España", "Suecia"], correcta: 1 },
  { pregunta: "¿Cómo se conoce el resultado de la final del Mundial 1950 para Brasil?", opciones: ["Maracanazo", "Vergüenza de Berna", "Mano de Dios", "Tragedia de Belo Horizonte"], correcta: 0 },
  { pregunta: "¿Qué país ganó el Mundial de 1954?", opciones: ["Hungría", "Alemania Occidental", "Austria", "Uruguay"], correcta: 1 },
  { pregunta: "¿Qué país ganó el Mundial de 1958?", opciones: ["Suecia", "Brasil", "Francia", "Gales"], correcta: 1 },
  { pregunta: "¿Qué jugador brasileño debutó como estrella mundial en el Mundial de 1958 con solo 17 años?", opciones: ["Pelé", "Garrincha", "Vavá", "Didí"], correcta: 0 },
  { pregunta: "¿Qué país ganó el Mundial de 1962?", opciones: ["Brasil", "Chile", "Checoslovaquia", "URSS"], correcta: 0 },
  { pregunta: "¿Qué país organizó el Mundial de 1962?", opciones: ["Chile", "Perú", "Argentina", "Brasil"], correcta: 0 },
  { pregunta: "¿Qué país ganó el Mundial de 1966?", opciones: ["Alemania Occidental", "Portugal", "Inglaterra", "URSS"], correcta: 2 },
  { pregunta: "¿Qué país organizó el Mundial de 1966?", opciones: ["Inglaterra", "Escocia", "Gales", "Irlanda"], correcta: 0 },
  { pregunta: "¿Qué país ganó el Mundial de 1970?", opciones: ["Italia", "Brasil", "Inglaterra", "Perú"], correcta: 1 },
  { pregunta: "¿Qué país organizó el Mundial de 1970?", opciones: ["México", "Argentina", "Chile", "Colombia"], correcta: 0 },
  { pregunta: "¿Qué país ganó el Mundial de 1974?", opciones: ["Holanda", "Alemania Occidental", "Polonia", "Brasil"], correcta: 1 },
  { pregunta: "¿Qué país organizó el Mundial de 1974?", opciones: ["Alemania Occidental", "Suiza", "Austria", "Bélgica"], correcta: 0 },
  { pregunta: "¿Qué país ganó el Mundial de 1978?", opciones: ["Holanda", "Argentina", "Brasil", "Perú"], correcta: 1 },
  { pregunta: "¿Qué país organizó el Mundial de 1978?", opciones: ["Argentina", "Uruguay", "Chile", "Brasil"], correcta: 0 },
  { pregunta: "¿Qué país ganó el Mundial de 1982?", opciones: ["Brasil", "Alemania Occidental", "Italia", "Francia"], correcta: 2 },
  { pregunta: "¿Qué país organizó el Mundial de 1982?", opciones: ["España", "Italia", "Portugal", "Francia"], correcta: 0 },
  { pregunta: "¿Qué país ganó el Mundial de 1990?", opciones: ["Argentina", "Alemania Occidental", "Italia", "Inglaterra"], correcta: 1 },
  { pregunta: "¿Qué país organizó el Mundial de 1990?", opciones: ["Italia", "España", "Francia", "Alemania"], correcta: 0 },
  { pregunta: "¿Qué selección fue subcampeona del Mundial de 1990 tras perder en penales?", opciones: ["Inglaterra", "Italia", "Holanda", "Yugoslavia"], correcta: 0 },
  { pregunta: "¿Cuántos goles anotó Just Fontaine en el Mundial de 1958, récord histórico?", opciones: ["11", "13", "9", "15"], correcta: 1 },
  { pregunta: "¿Qué jugador francés es el máximo goleador en un solo Mundial?", opciones: ["Just Fontaine", "Michel Platini", "Zinedine Zidane", "Thierry Henry"], correcta: 0 },
  { pregunta: "¿Qué selección eliminó a Alemania como local en semifinales del Mundial 2006?", opciones: ["Italia", "Francia", "Portugal", "Argentina"], correcta: 1 },
  { pregunta: "¿Quién recibió la tarjeta roja en la final del Mundial 2006 por un cabezazo?", opciones: ["Zinedine Zidane", "Marco Materazzi", "Fabio Cannavaro", "Thierry Henry"], correcta: 0 },
  { pregunta: "¿Qué país organizó el Mundial de 2006?", opciones: ["Alemania", "Francia", "Suiza", "Holanda"], correcta: 0 },
  { pregunta: "¿Cuántos goles anotó Ronaldo Nazário en el Mundial 2002, máximo goleador del torneo?", opciones: ["6", "7", "8", "5"], correcta: 2 },
  { pregunta: "¿Qué jugador alemán es el segundo máximo goleador histórico de los Mundiales?", opciones: ["Gerd Müller", "Miroslav Klose", "Lukas Podolski", "Thomas Müller"], correcta: 0 },
  { pregunta: "¿Cuántos goles anotó Pelé en Mundiales a lo largo de su carrera?", opciones: ["10", "12", "14", "16"], correcta: 1 },
  { pregunta: "¿Cuántos Mundiales ganó Pelé con Brasil?", opciones: ["2", "3", "4", "1"], correcta: 1 },
  { pregunta: "¿En qué Mundiales fue campeón Pelé?", opciones: ["1958, 1962 y 1970", "1958, 1966 y 1970", "1962, 1970 y 1974", "1950, 1958 y 1970"], correcta: 0 },
  { pregunta: "¿Qué jugador argentino marcó la 'Mano de Dios' en 1986?", opciones: ["Diego Maradona", "Jorge Burruchaga", "Mario Kempes", "Oscar Ruggeri"], correcta: 0 },
  { pregunta: "¿Quién anotó el gol decisivo en la final del Mundial 1986 para Argentina?", opciones: ["Diego Maradona", "Jorge Burruchaga", "Jorge Valdano", "Héctor Enrique"], correcta: 1 },
  { pregunta: "¿Cuántos Mundiales jugó la Selección de Costa Rica hasta 2022?", opciones: ["5", "6", "7", "8"], correcta: 2 },
  { pregunta: "¿En qué Mundial Costa Rica llegó a cuartos de final?", opciones: ["Brasil 2014", "Sudáfrica 2010", "Alemania 2006", "Rusia 2018"], correcta: 0 },
  { pregunta: "¿Quién fue el arquero héroe de Costa Rica en Brasil 2014?", opciones: ["Keylor Navas", "Patrick Pemberton", "Esteban Alvarado", "Leonel Moreira"], correcta: 0 },
  { pregunta: "¿Qué selecciones derrotó Costa Rica en la fase de grupos de Brasil 2014?", opciones: ["Italia y Uruguay", "Inglaterra y España", "Italia y Inglaterra", "Uruguay y España"], correcta: 3 },
  { pregunta: "¿Quién fue el goleador histórico de la Selección de Costa Rica?", opciones: ["Rolando Fonseca", "Paulo Wanchope", "Bryan Ruiz", "Joel Campbell"], correcta: 0 },
  { pregunta: "¿En qué Mundial debutó Brasil?", opciones: ["1930", "1934", "1938", "1950"], correcta: 0 },
  { pregunta: "¿Cuál es el único país que ha jugado todos los Mundiales?", opciones: ["Alemania", "Brasil", "Argentina", "Italia"], correcta: 1 },
  { pregunta: "¿Qué selección quedó subcampeona en 3 Mundiales consecutivos sin ganar ninguno (años 30s-50s aprox)?", opciones: ["Hungría", "Checoslovaquia", "Holanda", "Suecia"], correcta: 2 },
  { pregunta: "¿Qué selección perdió 3 finales de Mundial sin ganar ninguna (1974, 1978 y 2010)?", opciones: ["Holanda", "Alemania", "Argentina", "Italia"], correcta: 0 },
  { pregunta: "¿Qué jugador holandés es recordado por su 'jugada de la rabona' o por el gol de la final de 1974?", opciones: ["Johan Cruyff", "Johan Neeskens", "Ruud Krol", "Rob Rensenbrink"], correcta: 0 },
  { pregunta: "¿Qué selección fue conocida como 'La Naranja Mecánica'?", opciones: ["Holanda", "Bélgica", "Suecia", "Dinamarca"], correcta: 0 },
  { pregunta: "¿Cuál fue el equipo conocido como 'Los Diablos Rojos' en el Mundial 2018?", opciones: ["España", "Bélgica", "Croacia", "Inglaterra"], correcta: 1 },
  { pregunta: "¿Qué selección llegó a su primera final de Mundial en 2018, perdiendo ante Francia?", opciones: ["Croacia", "Bélgica", "Inglaterra", "Rusia"], correcta: 0 },
  { pregunta: "¿Quién fue el capitán de Francia campeón en 2018?", opciones: ["Hugo Lloris", "Antoine Griezmann", "Paul Pogba", "Kylian Mbappé"], correcta: 0 },
  { pregunta: "¿Qué jugador croata ganó el Balón de Oro del Mundial 2018?", opciones: ["Ivan Rakitic", "Luka Modric", "Mario Mandzukic", "Domagoj Vida"], correcta: 1 },
  { pregunta: "¿Qué arquero ganó el Guante de Oro en el Mundial 2018?", opciones: ["Thibaut Courtois", "Hugo Lloris", "Jordan Pickford", "Kepa Arrizabalaga"], correcta: 0 },
  { pregunta: "¿Qué arquero ganó el Guante de Oro en el Mundial 2022?", opciones: ["Emiliano Martínez", "Hugo Lloris", "Wojciech Szczesny", "Yassine Bounou"], correcta: 0 },
  { pregunta: "¿Quién anotó un hat-trick en la final del Mundial 2022?", opciones: ["Lionel Messi", "Kylian Mbappé", "Julián Álvarez", "Olivier Giroud"], correcta: 1 },
  { pregunta: "¿Cómo se definió la final del Mundial 2022 entre Argentina y Francia?", opciones: ["Tiempo extra", "Penales tras empate en tiempo extra", "Gol de oro", "Tiempo regular"], correcta: 1 },
  { pregunta: "¿Qué selección eliminó a España en penales en los octavos de final de Qatar 2022?", opciones: ["Marruecos", "Croacia", "Japón", "Portugal"], correcta: 1 },
  { pregunta: "¿Qué selección africana llegó a semifinales por primera vez en la historia en el Mundial 2022?", opciones: ["Marruecos", "Senegal", "Ghana", "Túnez"], correcta: 0 },
  { pregunta: "¿Cuál es el trofeo que se entrega al campeón del Mundial?", opciones: ["Copa Jules Rimet", "Copa FIFA", "Copa del Mundo (trofeo actual desde 1974)", "Copa Dorada"], correcta: 2 },
  { pregunta: "¿Cómo se llamaba el trofeo original del Mundial entre 1930 y 1970?", opciones: ["Copa Jules Rimet", "Copa de Oro", "Copa FIFA", "Copa Universal"], correcta: 0 },
  { pregunta: "¿Qué selección se quedó con la Copa Jules Rimet de forma permanente al ganar su tercer título?", opciones: ["Brasil", "Uruguay", "Italia", "Alemania"], correcta: 0 },
  { pregunta: "¿Qué mascota representó al Mundial de México 1986?", opciones: ["Pique", "Naranjito", "Footix", "Striker"], correcta: 0 },
  { pregunta: "¿Qué mascota representó al Mundial de España 1982?", opciones: ["Pique", "Naranjito", "Footix", "Juanito"], correcta: 1 },
  { pregunta: "¿Qué mascota representó al Mundial de Francia 1998?", opciones: ["Footix", "Striker", "Ato", "Fuleco"], correcta: 0 },
  { pregunta: "¿Qué mascota representó al Mundial de Brasil 2014?", opciones: ["Fuleco", "Zakumi", "Footix", "Goleo"], correcta: 0 },
  { pregunta: "¿Qué mascota representó al Mundial de Sudáfrica 2010?", opciones: ["Zakumi", "Fuleco", "Naranjito", "Gauchito"], correcta: 0 },
  { pregunta: "¿Qué balón oficial se usó en la final del Mundial 2022?", opciones: ["Al Rihla", "Telstar", "Brazuca", "Jabulani"], correcta: 0 },
  { pregunta: "¿Qué balón oficial se usó en el Mundial 2010, criticado por su comportamiento errático?", opciones: ["Jabulani", "Telstar", "Brazuca", "Tango"], correcta: 0 },
  { pregunta: "¿Cuántos jugadores conforman un equipo titular en la cancha?", opciones: ["10", "11", "12", "9"], correcta: 1 },
  { pregunta: "¿Cuántos minutos dura un partido de fútbol en tiempo regular?", opciones: ["80", "90", "100", "120"], correcta: 1 },
  { pregunta: "¿Qué selección ha llegado a más finales de Copa del Mundo?", opciones: ["Brasil", "Alemania", "Argentina", "Italia"], correcta: 1 },
  { pregunta: "¿Qué jugador es conocido como 'El Pibe de Oro'?", opciones: ["Diego Maradona", "Lionel Messi", "Carlos Valderrama", "Pelé"], correcta: 0 },
  { pregunta: "¿Qué jugador es apodado 'La Pulga'?", opciones: ["Cristiano Ronaldo", "Lionel Messi", "Neymar", "Luis Suárez"], correcta: 1 },
  { pregunta: "¿Cuántos Mundiales jugó Lionel Messi con Argentina?", opciones: ["3", "4", "5", "6"], correcta: 2 },
  { pregunta: "¿En qué Mundial Messi ganó su primer título mundial con la selección absoluta?", opciones: ["2014", "2018", "2022", "2010"], correcta: 2 },
  { pregunta: "¿Cuántos Mundiales jugó Cristiano Ronaldo hasta 2022?", opciones: ["4", "5", "6", "3"], correcta: 1 },
  { pregunta: "¿Qué selección eliminó a Portugal de Cristiano Ronaldo en octavos del Mundial 2022?", opciones: ["Marruecos", "Suiza", "Corea del Sur", "Ghana"], correcta: 1 },
  { pregunta: "¿En qué ciudad se jugó la final del Mundial 2022?", opciones: ["Doha", "Lusail", "Al Khor", "Education City"], correcta: 1 },
  { pregunta: "¿Qué jugador francés sufrió la final más dramática anotando un hat-trick pero perdiendo el título en 2022?", opciones: ["Antoine Griezmann", "Kylian Mbappé", "Olivier Giroud", "Ousmane Dembélé"], correcta: 1 },
  { pregunta: "¿Cuántas Copas del Mundo ha disputado la Selección de Costa Rica de forma consecutiva más reciente?", opciones: ["2", "3", "4", "1"], correcta: 1 },
  { pregunta: "¿Qué entrenador dirigió a Costa Rica en el histórico Mundial de Brasil 2014?", opciones: ["Jorge Luis Pinto", "Óscar Ramírez", "Gustavo Alfaro", "Paulo Wanchope"], correcta: 0 },
];

if (typeof module !== "undefined") module.exports = BANCO_TRIVIA;
